services:
  - type: web
    name: madrimovaibot
    env: python
    repo: https://github.com/InfoSchoolUz/madrimovaibot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_KEY
        sync: false
